USE provaci_db;

/*Passwords: root123*/

INSERT INTO user(
    username,
    name_surname,
    email,
    password,
    gender,
    orientation,
    born,
    profilePicture,
    biography,
    nationality,
    province,
    linkInstagram,
    linkFacebook,
    linkTelegram,
    linkSnapchat,
    linkTwitter,
    photography1,
    photography2,
    photography3,
    photography4,
    photography5,
    profession,
    verified
) VALUES (
    'SuperMario99',
    'Mario Rossi',
    'mario.rossi@gmail.com',
    '$2y$10$R4v9kJb7CcrEeM.vA9DgB.0rgkhFivRCYozpTpShMYDmDgJm8cwke',
    1,
    2,
    '1999-01-01',
    'img2.jpeg',
    'I am a super mario',
    'Italy',
    60,
    'https://www.instagram.com/mario.rossi/',
    'https://www.facebook.com/profile.php?id=100062591051707',
    'https://t.me/mario.rossi',
    'https://www.snapchat.com/add/mario.rossi',
    'https://twitter.com/mario.rossi',
    'post1.jpg',
    'post2.jpg',
    NULL,
    NULL,
    NULL,
    'Architetto',
    TRUE
), (
    'Mari78',
    'Mariangela Bianchi',
    'mari78@yahoo.com',
    '$2y$10$R4v9kJb7CcrEeM.vA9DgB.0rgkhFivRCYozpTpShMYDmDgJm8cwke',
    2,
    4,
    '1978-01-01',
    'img5.jpeg',
    'Hi, i love Pizza',
    'London',
    107,
    'https://www.instagram.com/mariangela.bianchi/',
    'https://www.facebook.com/mariangela.bianchi',
    NULL,
    NULL,
    NULL,
    'post3.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    'Ingegnere',
    TRUE
), (
    'Roby01',
    'Roberto Neri',
    'robertino@outlook.com',
    '$2y$10$R4v9kJb7CcrEeM.vA9DgB.0rgkhFivRCYozpTpShMYDmDgJm8cwke',
    1,
    1,
    '2001-01-01',
    'img3.jpeg',
    'Fu*k you, mother fuck*r!',
    'America',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'post4.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    'Sviluppatore',
    FALSE
), (
    'Pippolino',
    'Pippo Birbo',
    'pip@mail.com',
    '$2y$10$R4v9kJb7CcrEeM.vA9DgB.0rgkhFivRCYozpTpShMYDmDgJm8cwke',
    3,
    4,
    '2000-01-01',
    NULL,
    'Bisexual\n"In guerra, ogni buco è trincea!"',
    'Italy',
    NULL,
    'https://www.instagram.com/pippo.birbo/',
    NULL,
    NULL,
    NULL,
    'https://twitter.com/pippo.birbo',
    'post5.jpg',
    'post6.webp',
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE
), (
    'Nina000',
    'Paola Francesca Bianchi',
    'nina.paola@mail.com',
    '$2y$10$R4v9kJb7CcrEeM.vA9DgB.0rgkhFivRCYozpTpShMYDmDgJm8cwke',
    6,
    7,
    '2002-01-01',
    'img4.jpeg',
    'Ama il prossimo tuo come ami te stess*',
    'Nigeria',
    10,
    NULL,
    NULL,
    'https://t.me/nina.paola',
    NULL,
    NULL,
    'post7.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    'Attivista',
    TRUE
);

INSERT INTO user_pronoun(user_id, pronoun_id) VALUES
    ((SELECT id FROM user WHERE username='SuperMario99'), 1),
    ((SELECT id FROM user WHERE username='Pippolino'), 1),
    ((SELECT id FROM user WHERE username='Pippolino'), 2),
    ((SELECT id FROM user WHERE username='Pippolino'), 3),
    ((SELECT id FROM user WHERE username='Mari78'), 2),
    ((SELECT id FROM user WHERE username='Mari78'), 3),
    ((SELECT id FROM user WHERE username='Nina000'), 3);

INSERT INTO user_whatLookingFor(user_id, whatLookingFor_id) VALUES
    ((SELECT id FROM user WHERE username='SuperMario99'), 4),
    ((SELECT id FROM user WHERE username='Pippolino'), 1),
    ((SELECT id FROM user WHERE username='Pippolino'), 2),
    ((SELECT id FROM user WHERE username='Mari78'), 3),
    ((SELECT id FROM user WHERE username='Mari78'), 4),
    ((SELECT id FROM user WHERE username='Roby01'), 3);

INSERT INTO user_interest(user_id, interest_id) VALUES
    ((SELECT id FROM user WHERE username='SuperMario99'), 1),
    ((SELECT id FROM user WHERE username='SuperMario99'), 2),
    ((SELECT id FROM user WHERE username='SuperMario99'), 3),
    ((SELECT id FROM user WHERE username='SuperMario99'), 4),
    ((SELECT id FROM user WHERE username='SuperMario99'), 5),
    ((SELECT id FROM user WHERE username='SuperMario99'), 6),
    ((SELECT id FROM user WHERE username='SuperMario99'), 7),
    ((SELECT id FROM user WHERE username='SuperMario99'), 8),
    ((SELECT id FROM user WHERE username='SuperMario99'), 9),
    ((SELECT id FROM user WHERE username='SuperMario99'), 10),
    ((SELECT id FROM user WHERE username='Pippolino'), 2),
    ((SELECT id FROM user WHERE username='Pippolino'), 4),
    ((SELECT id FROM user WHERE username='Pippolino'), 6),
    ((SELECT id FROM user WHERE username='Pippolino'), 8),
    ((SELECT id FROM user WHERE username='Pippolino'), 10),
    ((SELECT id FROM user WHERE username='Pippolino'), 12),
    ((SELECT id FROM user WHERE username='Pippolino'), 14),
    ((SELECT id FROM user WHERE username='Pippolino'), 16),
    ((SELECT id FROM user WHERE username='Pippolino'), 18),
    ((SELECT id FROM user WHERE username='Pippolino'), 20),
    ((SELECT id FROM user WHERE username='Mari78'), 5),
    ((SELECT id FROM user WHERE username='Mari78'), 10),
    ((SELECT id FROM user WHERE username='Mari78'), 15),
    ((SELECT id FROM user WHERE username='Mari78'), 20),
    ((SELECT id FROM user WHERE username='Mari78'), 25),
    ((SELECT id FROM user WHERE username='Mari78'), 30),
    ((SELECT id FROM user WHERE username='Mari78'), 35),
    ((SELECT id FROM user WHERE username='Mari78'), 40),
    ((SELECT id FROM user WHERE username='Nina000'), 6),
    ((SELECT id FROM user WHERE username='Nina000'), 12),
    ((SELECT id FROM user WHERE username='Nina000'), 18),
    ((SELECT id FROM user WHERE username='Nina000'), 24),
    ((SELECT id FROM user WHERE username='Nina000'), 30),
    ((SELECT id FROM user WHERE username='Nina000'), 36),
    ((SELECT id FROM user WHERE username='Nina000'), 42),
    ((SELECT id FROM user WHERE username='Roby01'), 7),
    ((SELECT id FROM user WHERE username='Roby01'), 13),
    ((SELECT id FROM user WHERE username='Roby01'), 19),
    ((SELECT id FROM user WHERE username='Roby01'), 25),
    ((SELECT id FROM user WHERE username='Roby01'), 31),
    ((SELECT id FROM user WHERE username='Roby01'), 37),
    ((SELECT id FROM user WHERE username='Roby01'), 43);

INSERT INTO liked(userFrom_id, userTo_id) VALUES
    ((SELECT id FROM user WHERE username='SuperMario99'), (SELECT id FROM user WHERE username='Pippolino')),
    ((SELECT id FROM user WHERE username='SuperMario99'), (SELECT id FROM user WHERE username='Mari78')),
    ((SELECT id FROM user WHERE username='SuperMario99'), (SELECT id FROM user WHERE username='Nina000')),
    ((SELECT id FROM user WHERE username='Pippolino'), (SELECT id FROM user WHERE username='SuperMario99')),
    ((SELECT id FROM user WHERE username='Pippolino'), (SELECT id FROM user WHERE username='Mari78')),
    ((SELECT id FROM user WHERE username='Mari78'), (SELECT id FROM user WHERE username='SuperMario99')),
    ((SELECT id FROM user WHERE username='Mari78'), (SELECT id FROM user WHERE username='Pippolino')),
    ((SELECT id FROM user WHERE username='Mari78'), (SELECT id FROM user WHERE username='Roby01')),
    ((SELECT id FROM user WHERE username='Nina000'), (SELECT id FROM user WHERE username='SuperMario99')),
    ((SELECT id FROM user WHERE username='Nina000'), (SELECT id FROM user WHERE username='Pippolino')),
    ((SELECT id FROM user WHERE username='Roby01'), (SELECT id FROM user WHERE username='SuperMario99')),
    ((SELECT id FROM user WHERE username='Roby01'), (SELECT id FROM user WHERE username='Pippolino')),
    ((SELECT id FROM user WHERE username='Roby01'), (SELECT id FROM user WHERE username='Mari78'));